# Based on:
# https://github.com/ansible-community/molecule-docker/blob/v2.0.0/src/molecule_docker/playbooks/Dockerfile.j2

FROM {% if item.registry is defined -%}{{ item.registry.url -}}/{% endif -%}{{ item.image }}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

ENV DEBIAN_FRONTEND=noninteractive

RUN set -eux && \
  apt-get update -qq && \
  apt-get install -y \
    python3 \
    sudo \
    bash \
    ca-certificates \
    iproute2 \
    python3-apt \
    aptitude \
    systemd \
    systemd-cron && \
  apt-get clean && \
  rm -vrf /var/lib/apt/lists/*

ENV ANSIBLE_USER=ubuntu \
    DEPLOY_GROUP=deployer \
    SUDO_GROUP=sudo

RUN set -eux \
  && groupadd -r ${ANSIBLE_USER} \
  && groupadd -r ${DEPLOY_GROUP} \
  && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
  && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
  && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
  && sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers
